//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeChatService.ServiceReferenceFromJXFHu {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceFromJXFHu.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRockey", ReplyAction="*")]
        bool CheckRockey();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRockey", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckRockeyAsync();
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 AutoCompleteResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoComplete", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteResponse AutoComplete(MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoComplete", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteResponse> AutoCompleteAsync(MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginCheck", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckResponse LoginCheck(MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckResponse> LoginCheckAsync(MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 equpmentCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZJRFCheck", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckResponse ZJRFCheck(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZJRFCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckResponse> ZJRFCheckAsync(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 contractBianHao 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZJRFCheckAccordContractNo", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoResponse ZJRFCheckAccordContractNo(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZJRFCheckAccordContractNo", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoResponse> ZJRFCheckAccordContractNoAsync(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 s 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dstring", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.DstringResponse Dstring(MyWeChatService.ServiceReferenceFromJXFHu.DstringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dstring", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.DstringResponse> DstringAsync(MyWeChatService.ServiceReferenceFromJXFHu.DstringRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 s 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Estring", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.EstringResponse Estring(MyWeChatService.ServiceReferenceFromJXFHu.EstringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Estring", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.EstringResponse> EstringAsync(MyWeChatService.ServiceReferenceFromJXFHu.EstringRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pwd 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryContract", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.QueryContractResponse QueryContract(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryContract", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.QueryContractResponse> QueryContractAsync(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pwd 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryContractLog", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogResponse QueryContractLog(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryContractLog", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogResponse> QueryContractLogAsync(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 equpmentCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JXRFCheck", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckResponse JXRFCheck(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JXRFCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckResponse> JXRFCheckAsync(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 equpmentCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JXRFCheckLog", ReplyAction="*")]
        MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogResponse JXRFCheckLog(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JXRFCheckLog", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogResponse> JXRFCheckLogAsync(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoComplete", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequestBody Body;
        
        public AutoCompleteRequest() {
        }
        
        public AutoCompleteRequest(MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoCompleteRequestBody {
        
        public AutoCompleteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoCompleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteResponseBody Body;
        
        public AutoCompleteResponse() {
        }
        
        public AutoCompleteResponse(MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoCompleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoCompleteResult;
        
        public AutoCompleteResponseBody() {
        }
        
        public AutoCompleteResponseBody(string AutoCompleteResult) {
            this.AutoCompleteResult = AutoCompleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCheck", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequestBody Body;
        
        public LoginCheckRequest() {
        }
        
        public LoginCheckRequest(MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginCheckRequestBody() {
        }
        
        public LoginCheckRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckResponseBody Body;
        
        public LoginCheckResponse() {
        }
        
        public LoginCheckResponse(MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginCheckResult;
        
        public LoginCheckResponseBody() {
        }
        
        public LoginCheckResponseBody(string LoginCheckResult) {
            this.LoginCheckResult = LoginCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZJRFCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZJRFCheck", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequestBody Body;
        
        public ZJRFCheckRequest() {
        }
        
        public ZJRFCheckRequest(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZJRFCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string equpmentCode;
        
        public ZJRFCheckRequestBody() {
        }
        
        public ZJRFCheckRequestBody(string equpmentCode) {
            this.equpmentCode = equpmentCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZJRFCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZJRFCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckResponseBody Body;
        
        public ZJRFCheckResponse() {
        }
        
        public ZJRFCheckResponse(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZJRFCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZJRFCheckResult;
        
        public ZJRFCheckResponseBody() {
        }
        
        public ZJRFCheckResponseBody(string ZJRFCheckResult) {
            this.ZJRFCheckResult = ZJRFCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZJRFCheckAccordContractNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZJRFCheckAccordContractNo", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequestBody Body;
        
        public ZJRFCheckAccordContractNoRequest() {
        }
        
        public ZJRFCheckAccordContractNoRequest(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZJRFCheckAccordContractNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contractBianHao;
        
        public ZJRFCheckAccordContractNoRequestBody() {
        }
        
        public ZJRFCheckAccordContractNoRequestBody(string contractBianHao) {
            this.contractBianHao = contractBianHao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZJRFCheckAccordContractNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZJRFCheckAccordContractNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoResponseBody Body;
        
        public ZJRFCheckAccordContractNoResponse() {
        }
        
        public ZJRFCheckAccordContractNoResponse(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZJRFCheckAccordContractNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZJRFCheckAccordContractNoResult;
        
        public ZJRFCheckAccordContractNoResponseBody() {
        }
        
        public ZJRFCheckAccordContractNoResponseBody(string ZJRFCheckAccordContractNoResult) {
            this.ZJRFCheckAccordContractNoResult = ZJRFCheckAccordContractNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DstringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Dstring", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.DstringRequestBody Body;
        
        public DstringRequest() {
        }
        
        public DstringRequest(MyWeChatService.ServiceReferenceFromJXFHu.DstringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DstringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public DstringRequestBody() {
        }
        
        public DstringRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DstringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DstringResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.DstringResponseBody Body;
        
        public DstringResponse() {
        }
        
        public DstringResponse(MyWeChatService.ServiceReferenceFromJXFHu.DstringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DstringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DstringResult;
        
        public DstringResponseBody() {
        }
        
        public DstringResponseBody(string DstringResult) {
            this.DstringResult = DstringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Estring", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.EstringRequestBody Body;
        
        public EstringRequest() {
        }
        
        public EstringRequest(MyWeChatService.ServiceReferenceFromJXFHu.EstringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public EstringRequestBody() {
        }
        
        public EstringRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstringResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.EstringResponseBody Body;
        
        public EstringResponse() {
        }
        
        public EstringResponse(MyWeChatService.ServiceReferenceFromJXFHu.EstringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EstringResult;
        
        public EstringResponseBody() {
        }
        
        public EstringResponseBody(string EstringResult) {
            this.EstringResult = EstringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryContract", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequestBody Body;
        
        public QueryContractRequest() {
        }
        
        public QueryContractRequest(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryContractRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contractNo;
        
        public QueryContractRequestBody() {
        }
        
        public QueryContractRequestBody(string pwd, string contractNo) {
            this.pwd = pwd;
            this.contractNo = contractNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryContractResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.QueryContractResponseBody Body;
        
        public QueryContractResponse() {
        }
        
        public QueryContractResponse(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryContractResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryContractResult;
        
        public QueryContractResponseBody() {
        }
        
        public QueryContractResponseBody(string QueryContractResult) {
            this.QueryContractResult = QueryContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryContractLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryContractLog", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequestBody Body;
        
        public QueryContractLogRequest() {
        }
        
        public QueryContractLogRequest(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryContractLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contractNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userName;
        
        public QueryContractLogRequestBody() {
        }
        
        public QueryContractLogRequestBody(string pwd, string contractNo, string userName) {
            this.pwd = pwd;
            this.contractNo = contractNo;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryContractLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryContractLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogResponseBody Body;
        
        public QueryContractLogResponse() {
        }
        
        public QueryContractLogResponse(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryContractLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryContractLogResult;
        
        public QueryContractLogResponseBody() {
        }
        
        public QueryContractLogResponseBody(string QueryContractLogResult) {
            this.QueryContractLogResult = QueryContractLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JXRFCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JXRFCheck", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequestBody Body;
        
        public JXRFCheckRequest() {
        }
        
        public JXRFCheckRequest(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JXRFCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string equpmentCode;
        
        public JXRFCheckRequestBody() {
        }
        
        public JXRFCheckRequestBody(string equpmentCode) {
            this.equpmentCode = equpmentCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JXRFCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JXRFCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckResponseBody Body;
        
        public JXRFCheckResponse() {
        }
        
        public JXRFCheckResponse(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JXRFCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JXRFCheckResult;
        
        public JXRFCheckResponseBody() {
        }
        
        public JXRFCheckResponseBody(string JXRFCheckResult) {
            this.JXRFCheckResult = JXRFCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JXRFCheckLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JXRFCheckLog", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequestBody Body;
        
        public JXRFCheckLogRequest() {
        }
        
        public JXRFCheckLogRequest(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JXRFCheckLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string equpmentCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        public JXRFCheckLogRequestBody() {
        }
        
        public JXRFCheckLogRequestBody(string equpmentCode, string userName) {
            this.equpmentCode = equpmentCode;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JXRFCheckLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JXRFCheckLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogResponseBody Body;
        
        public JXRFCheckLogResponse() {
        }
        
        public JXRFCheckLogResponse(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JXRFCheckLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JXRFCheckLogResult;
        
        public JXRFCheckLogResponseBody() {
        }
        
        public JXRFCheckLogResponseBody(string JXRFCheckLogResult) {
            this.JXRFCheckLogResult = JXRFCheckLogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap>, MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckRockey() {
            return base.Channel.CheckRockey();
        }
        
        public System.Threading.Tasks.Task<bool> CheckRockeyAsync() {
            return base.Channel.CheckRockeyAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.AutoComplete(MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequest request) {
            return base.Channel.AutoComplete(request);
        }
        
        public string AutoComplete() {
            MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequestBody();
            MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).AutoComplete(inValue);
            return retVal.Body.AutoCompleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.AutoCompleteAsync(MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequest request) {
            return base.Channel.AutoCompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteResponse> AutoCompleteAsync() {
            MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.AutoCompleteRequestBody();
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).AutoCompleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.LoginCheck(MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequest request) {
            return base.Channel.LoginCheck(request);
        }
        
        public string LoginCheck(string username, string password) {
            MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).LoginCheck(inValue);
            return retVal.Body.LoginCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.LoginCheckAsync(MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequest request) {
            return base.Channel.LoginCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckResponse> LoginCheckAsync(string username, string password) {
            MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.LoginCheckRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).LoginCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.ZJRFCheck(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequest request) {
            return base.Channel.ZJRFCheck(request);
        }
        
        public string ZJRFCheck(string equpmentCode) {
            MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequestBody();
            inValue.Body.equpmentCode = equpmentCode;
            MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).ZJRFCheck(inValue);
            return retVal.Body.ZJRFCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.ZJRFCheckAsync(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequest request) {
            return base.Channel.ZJRFCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckResponse> ZJRFCheckAsync(string equpmentCode) {
            MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckRequestBody();
            inValue.Body.equpmentCode = equpmentCode;
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).ZJRFCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.ZJRFCheckAccordContractNo(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequest request) {
            return base.Channel.ZJRFCheckAccordContractNo(request);
        }
        
        public string ZJRFCheckAccordContractNo(string contractBianHao) {
            MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequestBody();
            inValue.Body.contractBianHao = contractBianHao;
            MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).ZJRFCheckAccordContractNo(inValue);
            return retVal.Body.ZJRFCheckAccordContractNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.ZJRFCheckAccordContractNoAsync(MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequest request) {
            return base.Channel.ZJRFCheckAccordContractNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoResponse> ZJRFCheckAccordContractNoAsync(string contractBianHao) {
            MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.ZJRFCheckAccordContractNoRequestBody();
            inValue.Body.contractBianHao = contractBianHao;
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).ZJRFCheckAccordContractNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.DstringResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.Dstring(MyWeChatService.ServiceReferenceFromJXFHu.DstringRequest request) {
            return base.Channel.Dstring(request);
        }
        
        public string Dstring(string s) {
            MyWeChatService.ServiceReferenceFromJXFHu.DstringRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.DstringRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.DstringRequestBody();
            inValue.Body.s = s;
            MyWeChatService.ServiceReferenceFromJXFHu.DstringResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).Dstring(inValue);
            return retVal.Body.DstringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.DstringResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.DstringAsync(MyWeChatService.ServiceReferenceFromJXFHu.DstringRequest request) {
            return base.Channel.DstringAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.DstringResponse> DstringAsync(string s) {
            MyWeChatService.ServiceReferenceFromJXFHu.DstringRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.DstringRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.DstringRequestBody();
            inValue.Body.s = s;
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).DstringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.EstringResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.Estring(MyWeChatService.ServiceReferenceFromJXFHu.EstringRequest request) {
            return base.Channel.Estring(request);
        }
        
        public string Estring(string s) {
            MyWeChatService.ServiceReferenceFromJXFHu.EstringRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.EstringRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.EstringRequestBody();
            inValue.Body.s = s;
            MyWeChatService.ServiceReferenceFromJXFHu.EstringResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).Estring(inValue);
            return retVal.Body.EstringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.EstringResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.EstringAsync(MyWeChatService.ServiceReferenceFromJXFHu.EstringRequest request) {
            return base.Channel.EstringAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.EstringResponse> EstringAsync(string s) {
            MyWeChatService.ServiceReferenceFromJXFHu.EstringRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.EstringRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.EstringRequestBody();
            inValue.Body.s = s;
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).EstringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.QueryContractResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.QueryContract(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequest request) {
            return base.Channel.QueryContract(request);
        }
        
        public string QueryContract(string pwd, string contractNo) {
            MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequestBody();
            inValue.Body.pwd = pwd;
            inValue.Body.contractNo = contractNo;
            MyWeChatService.ServiceReferenceFromJXFHu.QueryContractResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).QueryContract(inValue);
            return retVal.Body.QueryContractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.QueryContractResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.QueryContractAsync(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequest request) {
            return base.Channel.QueryContractAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.QueryContractResponse> QueryContractAsync(string pwd, string contractNo) {
            MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.QueryContractRequestBody();
            inValue.Body.pwd = pwd;
            inValue.Body.contractNo = contractNo;
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).QueryContractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.QueryContractLog(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequest request) {
            return base.Channel.QueryContractLog(request);
        }
        
        public string QueryContractLog(string pwd, string contractNo, string userName) {
            MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequestBody();
            inValue.Body.pwd = pwd;
            inValue.Body.contractNo = contractNo;
            inValue.Body.userName = userName;
            MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).QueryContractLog(inValue);
            return retVal.Body.QueryContractLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.QueryContractLogAsync(MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequest request) {
            return base.Channel.QueryContractLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogResponse> QueryContractLogAsync(string pwd, string contractNo, string userName) {
            MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.QueryContractLogRequestBody();
            inValue.Body.pwd = pwd;
            inValue.Body.contractNo = contractNo;
            inValue.Body.userName = userName;
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).QueryContractLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.JXRFCheck(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequest request) {
            return base.Channel.JXRFCheck(request);
        }
        
        public string JXRFCheck(string equpmentCode) {
            MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequestBody();
            inValue.Body.equpmentCode = equpmentCode;
            MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).JXRFCheck(inValue);
            return retVal.Body.JXRFCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.JXRFCheckAsync(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequest request) {
            return base.Channel.JXRFCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckResponse> JXRFCheckAsync(string equpmentCode) {
            MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckRequestBody();
            inValue.Body.equpmentCode = equpmentCode;
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).JXRFCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogResponse MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.JXRFCheckLog(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequest request) {
            return base.Channel.JXRFCheckLog(request);
        }
        
        public string JXRFCheckLog(string equpmentCode, string userName) {
            MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequestBody();
            inValue.Body.equpmentCode = equpmentCode;
            inValue.Body.userName = userName;
            MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogResponse retVal = ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).JXRFCheckLog(inValue);
            return retVal.Body.JXRFCheckLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogResponse> MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap.JXRFCheckLogAsync(MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequest request) {
            return base.Channel.JXRFCheckLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogResponse> JXRFCheckLogAsync(string equpmentCode, string userName) {
            MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequest inValue = new MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequest();
            inValue.Body = new MyWeChatService.ServiceReferenceFromJXFHu.JXRFCheckLogRequestBody();
            inValue.Body.equpmentCode = equpmentCode;
            inValue.Body.userName = userName;
            return ((MyWeChatService.ServiceReferenceFromJXFHu.Service1Soap)(this)).JXRFCheckLogAsync(inValue);
        }
    }
}
